### ISSUE TITLE
Excuse me,it unable to add to discord servers

### ISSUE THREAD

**Issue by darron1220** [eartharoid/discord-media-helper#2] opened 2023-11-22 09:13 UTC
![image](https://github.com/eartharoid/discord-media-helper/assets/67164842/67eade54-614b-45a8-817c-93063eea85c2)

**Comment by eartharoid** [comment] 2023-11-22 20:27
Duplicate of #1

**Comment by eartharoid** [comment] 2023-11-22 20:27
I'm not sure when this will be fixed

**Comment by eartharoid** [comment] 2024-05-09 13:09
@darron1220 the bot is now verified and can be added at https://discord.com/oauth2/authorize?client_id=1026547091121655808&permissions=274878032960&scope=bot%20applications.commands

**Closed by eartharoid** 2024-05-09 13:09 UTC

**Comment by darron1220** [comment] 2024-05-09 14:33
Thank you
